stages:
  - build
  - static_analysis   # New stage for static analysis
  - test
  - cleanup

# Define the base image
image: node:16  # Use Node.js for building and testing

default:
  tags: 
    - node

# Build Stage
build:
  stage: build
  script:
    - echo "Starting Build Stage"
    - cd service1
    - npm install
    - echo "Build completed successfully!"
  rules:
    - if: $CI_COMMIT_BRANCH == "project"  # Ensure the pipeline runs on the correct branch
    - if: $CI_PIPELINE_SOURCE == "push"  # Allow jobs triggered by a push event

# Static Analysis Stage
static_analysis:
  stage: static_analysis  # New stage for static analysis
  script:
    - echo "Running Static Analysis (ESLint)"
    - cd service1
    - npm install  # Ensure dependencies (including ESLint) are installed
    - npx eslint "src/**/*.{js,jsx,ts,tsx}" # Run ESLint on specific files/folder
  rules:
    - if: $CI_COMMIT_BRANCH == "project"  # Ensure the pipeline runs on the correct branch
    - if: $CI_PIPELINE_SOURCE == "push"  # Allow jobs triggered by a push event


# Test Stage
test:
  stage: test
  before_script:
    - echo "Installing dependencies..."
    - cd service1
    - npm install
  script:
    - echo "Running Tests"
    - npx mocha
  rules:
    - if: $CI_COMMIT_BRANCH == "project"  # Ensure the pipeline runs on the correct branch
    - if: $CI_PIPELINE_SOURCE == "push"  # Allow jobs triggered by a push event

# Cleanup Stage (Optional)
cleanup:
  stage: cleanup
  script:
    - echo "Stopping old Docker containers"
    - docker compose down || true
  when: manual  # Manual trigger required for cleanup
  rules:
    - if: $CI_COMMIT_BRANCH == "project"  # Ensure the pipeline runs on the correct branch
    - if: $CI_PIPELINE_SOURCE == "push"  # Allow jobs triggered by a push event
