services:
  service1-1:
    build: ./service1
    container_name: service1-1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - mynetwork
    command: /bin/sh -c "sleep 2 && npm start"
    depends_on:
      - db
    restart: always
    user: root

  service1-2:
    build: ./service1
    container_name: service1-2
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - mynetwork
    command: /bin/sh -c "sleep 2 && npm start"
    depends_on:
      - db
    restart: always
    user: root

  service1-3:
    build: ./service1
    container_name: service1-3
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - mynetwork
    command: /bin/sh -c "sleep 2 && npm start"
    depends_on:
      - db
    restart: always
    user: root

  service2:
    build: ./service2
    container_name: service2
    networks:
      - mynetwork
    depends_on:
      - db
    restart: always
    ports:
      - "5000:5000"

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8197:8197"
    networks:
      - mynetwork
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/.htpasswd:/etc/nginx/.htpasswd
      - ./nginx/index.html:/usr/share/nginx/html/index.html
    depends_on:
      - service1-1
      - service1-2
      - service1-3

  db:
    image: mongo:latest
    container_name: mongo-db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=mydatabase
    networks:
      - mynetwork
    volumes:
      - mongodb-data:/data/db
    ports:
      - "27017:27017"

networks:
  mynetwork:
    driver: bridge

volumes:
  mongodb-data:
