worker_processes 1;

events { worker_connections 1024; }

http {
    upstream service1 {
        server service1-1:8199;
        server service1-2:8199;
        server service1-3:8199;
    }

    upstream service2 {
        server service2:5000;
    }

    server {
        listen 8197;

        location / {
            root /usr/share/nginx/html;
            index index.html;
            try_files $uri /index.html; # Fallback to index.html for SPA
        }

        # Serve static files
        location /static/ {
            root /usr/share/nginx/html;
        }

        # Restrict /state route to authenticated users for changing state
        location /state {
            proxy_pass http://service1;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

            # Apply authentication for PUT requests
            # if ($request_method = PUT) {
            #     auth_basic "Restricted State Change";
            #     auth_basic_user_file /etc/nginx/.htpasswd;
            # }
        }

        # Proxy /request to Service1
        location /request {
            proxy_pass http://service1;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        # Proxy /run-log to Service1
        location /run-log {
            proxy_pass http://service1;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        # Proxy /info to Service2
        location /info {
            proxy_pass http://service2;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        location /stop {
            proxy_pass http://service1-1;
            proxy_set_header Host $host;
        }
    }
}