worker_processes 1;

events { worker_connections 1024; }

http {
    server {
        listen 8198;

        # Serve the frontend HTML page
        location / {
            root /usr/share/nginx/html;
            index index.html;
            try_files $uri /index.html; # Fallback to index.html for SPA
        }

        # Serve static files
        location /static/ {
            root /usr/share/nginx/html;
        }

        location /request {
            proxy_pass http://service1;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        # Direct /stop to one instance of Service1
        location /stop {
            proxy_pass http://service1-1:8199/stop;
            proxy_set_header Host $host;
        }
    }
}

